### ISSUE TITLE
Crash when tried to sleep

### ISSUE THREAD

**Issue by thegamerx1** [modmuss50/JustSleep#7] opened 2019-07-17 03:34 UTC
https://pastebin.com/KZksiSFR
Game crashed after trying to sleep 2 time in day fix pls
edit:
for some reason tlauncher says im using windows 8 but im actually using windows 10

**Comment by hugeblank** [comment] 2019-08-10 18:45
Duplicate of #6

**Comment by thegamerx1** [comment] 2019-08-18 11:59
Right

**Closed as completed** 2019-08-18 12:00 UTC
